connector.name=delta_lake
hive.metastore=thrift
hive.metastore.uri=thrift://lh-hive:9083
delta.enable-non-concurrent-writes=true
fs.native-local.enabled=true
delta.register-table-procedure.enabled=true
