connector.name=delta_lake
hive.metastore.uri=thrift://lh_hive:9083
hive.s3.endpoint=http://lh_minio:9000
hive.s3.path-style-access=true
hive.s3.aws-access-key=minioadmin
hive.s3.aws-secret-key=minioadmin123
hive.s3.ssl.enabled=false
delta.metadata.live-files.cache-size=100MB
