FROM apache/spark:3.5.1-python3

USER root
RUN pip install delta-spark==3.2.0 --no-cache-dir \
    && useradd -m -u 2000 sparkuser \
    && mkdir -p /opt/spark/logs /opt/spark/work-dir/data \
    && chown -R 2000:2000 /opt/spark /opt/spark/logs /opt/spark/work-dir

COPY --chown=2000:2000 spark-init.sh /opt/spark/work-dir/spark-init.sh

USER 2000